name: Nota fixed-origin smoke

on:
  push:
    branches: [development]

permissions:
  contents: read
  id-token: write

jobs:
  nota-static-smoke:
    uses: 0DFxinc/nota-github/.github/workflows/run-static-smoke.yml@597db4220d09aefb94909814e5bb9f6e72362795
    with:
      policy-id: 00000000-0000-4000-8000-000000000000
      nota-environment: development
